### ISSUE TITLE
Row offset on export keeps giving error

### ISSUE THREAD

**Issue by rachellyne** [intermine/intermine#1300] opened 2016-02-16 11:34 UTC
"Error The offset is greater than the total number of results".

Can fix by moving the slider, but it's annoying.

**Comment by julie-sullivan** [comment] 2016-02-16 11:36
Can you tell me which mine you were using and which query you are running?

Can you reproduce the error?

**Comment by rachellyne** [comment] 2016-02-16 12:01
Oh yes vital detail - HumanMine (live and beta), although I haven't checked other mines.  It happens nearly every time I try to export a list.

**Comment by julie-sullivan** [comment] 2016-11-14 16:52
@rachellyne I tried just now and it worked (on live humanmine with a list of 94 genes. Can you try again?

I have seen this on queries with millions of rows. It seems like the count takes a minute to catch up so the error is displayed until the final count is corrected. @yochannah I think this is reported on another ticket.

**Comment by julie-sullivan** [comment] 2016-11-14 16:56
Here's the ticket I was thinking of:  #1268. Is that a duplicate?

**Comment by julie-sullivan** [comment] 2017-04-06 15:43
Yes, this is a duplicate of  #1268.

**Closed by julie-sullivan** 2017-04-06 15:43 UTC
Labels: bug, duplicate
