### ISSUE TITLE
Concurrent modification issues in object-store writers

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#557] opened 2014-03-05 10:39 UTC
Concurrent modification exceptions are inevitable when you have multiple users making requests to a service and some of them are modifying the UOSW (creating bags, deleting resources, etc). This causes 500 errors which are impossible for end users to interpret.

This seems mostly due to the singleton nature of the `uosw` and the way it manages consistency and transactions. All changes are reflected in a monotonic sequence, which means that the application is responsible for ensuring consistency, rather than relying on db transactions to achieve this.

**Comment by julie-sullivan** [comment] 2015-01-21 16:38
Duplicate of #225

**Closed** 2015-06-04 09:49 UTC
Labels: duplicate
