### ISSUE TITLE
Save XML button gives "Bad URL" in Safari

### ISSUE THREAD

**Issue by JoelRichardson** [intermine/intermine#420] opened 2013-08-21 20:06 UTC
Seems to be specific to safari. Chrome works fine.
From a results table, click "Code", then "XML", then "Save".
You get an error from Safari: "Can't open blob:http://www.flymine.org/... because OS X does not recognize internet addresses starting with 'blob:'"

**Comment by julie-sullivan** [comment] 2015-03-06 17:07
This is working in beta.

@JoelRichardson This fix will be part of InterMine 1.5 release.

**Comment by julie-sullivan** [comment] 2015-05-20 12:41
@joshkh I get a file download but the file is empty. This is only for Safari with XML. All other browsers and languages seem fine. There is no error in the console or tomcat logs.

**Comment by julie-sullivan** [comment] 2015-10-09 14:00
@joshkh @yochannah Can we confirm this is still a problem?

**Comment by yochannah** [comment] 2015-10-09 14:12
I just tried exporting a file in xml format in Safari 8.0.4, and it seems to have downloaded and populated the file ok. 

To download the file I went to a results page, clicked 'Export', selected 'Download TSV file', then changed it to XML format instead. I am not sure if this was the right thing to do to reproduce - the UI may have changed since this bug was logged?

**Comment by julie-sullivan** [comment] 2015-10-09 14:13
@yochannah Thanks! So it looks like it's been fixed. I'll ask @JoelRichardson to test once we've got a release candidate.

**Closed by julie-sullivan** 2015-10-09 14:13 UTC
Labels: bug
