### ISSUE TITLE
Meta web services for BlueGenes

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1484] opened 2016-12-19 13:31 UTC
A service to clearly report whether or not a basic intermine service is configured and in use would be useful  for bluegenes. 

For example, ZebrafishMine and RatMine don't support region search. At the moment I can work around this by using a config file specifying which mines support it, but it would be better to get this from the mines themselves. Something like 

```
GET /service/service-enabled/regionsearch
 -> 
true
```

or perhaps this, which is more concise and would require fewer individual requests

```
GET /service/enabled-services/
-> 
["region search", "widgets", "templates"]
```

etc... 

This would be useful for region search, templates, lists, widgets (I know you can get a list of widgets, but it would be nice to be consistent with the others.). I'm guessing any mine with a valid model *will* have a querybuilder so we probably don't need to check that. @joshkh can you think of any other to add?

This isn't something that should be abstracted to an intermine registry, for the same reasons that it's not good in a config file - it should be automatic, supplied by the mine, so it's never out of date if the mine gets updated.

**Comment by julie-sullivan** [comment] 2017-03-22 11:23
http://iodocs.apps.intermine.org/flymine-beta/docs#/ws-service-listing/GET/

Isn't this information available in the service listing? Or do you need more information?

**Comment by yochannah** [comment] 2017-03-22 11:48
This does most of it, but a few questions:

- if the mine has no service x (i.e. enrichment widgets) and no intentions of it being added will its endpoint still be exposed by this service?
- region search should probably be added.

**Comment by julie-sullivan** [comment] 2017-04-07 13:13
* it uses the web.xml from each mine, so will list only the enabled endpoints
* i see the region search end points. Which ones are missing?

**Comment by julie-sullivan** [comment] 2017-04-27 14:33
duplicate of #703

**Closed by julie-sullivan** 2017-04-27 14:33 UTC
