### ISSUE TITLE
Gradle 4.1 is to old for Java 11

### ISSUE THREAD

**Issue by nauer** [intermine/intermine#1915] opened 2018-10-15 11:24 UTC
Please update `gradlew` to the actual version. Gradle 4.1 is not compatible with Java 11. You need at minimum version 4.7. If not you get this error: 
    `Could not determine Java version using executable /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java`

**Comment by danielabutano** [comment] 2018-10-18 14:09
We need to replace distributionUrl=https\://services.gradle.org/distributions/gradle-4.9-all.zip
in all the gradle-wrapper.properties files

**Comment by julie-sullivan** [comment] 2018-10-22 11:50
I got some warnings:

```
The following annotation processors were detected on the compile classpath: 'org.apache.logging.log4j.core.config.plugins.processor.PluginProcessor'. Detecting annotation processors on the compile classpath is deprecated and Gradle 5.0 will ignore them. Please add them to the annotation processor path instead. If you did not intend to use annotation processors, you can use the '-proc:none' compiler argument to ignore them.
```

**Comment by julie-sullivan** [comment] 2018-10-22 11:52
```
julie ~/git/flymine $ ./gradlew builddb --warning-mode all

> Configure project :
Using properties file: '/local-homes/julie/.intermine/flymine.properties'
The FileCollection.stopExecutionIfEmpty() method has been deprecated and is scheduled to be removed in Gradle 5.0.
        at build_276f5lx8731sdlxujrf3uo5bm$_run_closure2$_closure6.doCall(/local-data/git/flymine/build.gradle:55)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

**Comment by julie-sullivan** [comment] 2019-02-26 16:48
https://docs.gradle.org/current/userguide/upgrading_version_4.html

**Comment by julie-sullivan** [comment] 2019-05-15 12:38
@danielabutano since `FileCollection.stopExecutionIfEmpty()` has been deprecated, I am going to remove so we can upgrade. Is that all right? It was deprecated without a replacement.

**Comment by danielabutano** [comment] 2019-05-15 12:42
ok for me. Don't remember where we used id, but maybe replace that with a blocking execution check where appropriate....

**Comment by julie-sullivan** [comment] 2019-05-15 12:47
what do you mean? I don't see the syntax for that.

Do you mean to check if that properties file is there and then fail if it is not? Won't it fail anyway? So why check?

Okay I will leave this with you then, but we have to do this sooner rather than later because it's blocking the increasingly popular Java 11. :)

**Comment by danielabutano** [comment] 2019-09-04 16:28
added
compileJava {
        options.compilerArgs += ["-proc:none"]
    }
as suggested [here](https://discuss.gradle.org/t/regarding-the-annotation-processors-on-compile-classpath-warning-in-gradle-4-6/26144)

**Comment by julie-sullivan** [comment] 2019-09-05 12:39
This is the command I used to upgradle:

```
export GRADLE="4.9"; (cd plugin/ && ./gradlew wrapper --gradle-version=$GRADLE) && (cd intermine && ./gradlew wrapper --gradle-version=$GRADLE) && (cd bio && ./gradlew wrapper --gradle-version=$GRADLE) && (cd bio/sources && ./gradlew wrapper --gradle-version=$GRADLE)
```

**Comment by danielabutano** [comment] 2019-09-05 12:40
I used the same

**Comment by julie-sullivan** [comment] 2019-09-05 14:58
When I run `mergeModels` locally, no error is generated:
```
./gradlew bio-source-uniprot:clean 
./gradlew bio-source-uniprot:mergeModels
```
(this fails on travis however)

There are two model files generated:

```
./build/tmp/expandedArchives/bio-model-4.0.1.jar_1a5d4383b595a221cefd66a99a448527/genomic_model.xml
./build/resources/main/genomic_model.xml
```

1. the genomic model from the JAR is empty
2. the genomic model from the `build/resources` directory is ONLY the additions file -- in this case from the UniProt source. 

This file should be the model+the additions file merged as `mergeModels` is merging these files together:

```
# merge models
ant.mergeBioSourceModel(inputModelFile: inputModelFilePath, 
additionsFile: bioSourceAdditionsFile,
outputFile: inputModelFilePath)
```

If I run the `mergeModels` task again, BOTH files will be empty.

The only thing I can think of is that Gradle 4.9 handles system properties differently, and we aren't able to read XML properly because this property is lost:

```
systemProp.javax.xml.stream.XMLOutputFactory=com.sun.xml.internal.stream.XMLOutputFactoryImpl
```
I'll now try different gradle versions. Maybe look at the release notes to see if that has changed. We do read SOME XML sometimes, so it has to be specific to bio-sources.

**Comment by danielabutano** [comment] 2019-09-05 17:25
I think the issue is related to the processresources task which, for some reason doesn't work properly.
If you execute `./gradlew processresources` you have this error
Task ':bio-source-biogrid:processResources' is not up-to-date because:
  Output property 'destinationDir' file /home/FILESERVER5/micklem/db539/Projects/git/intermine-git-gradle/intermine/bio/sources/biogrid/build/resources/main has been removed.
  Output property 'destinationDir' file /home/FILESERVER5/micklem/db539/Projects/git/intermine-git-gradle/intermine/bio/sources/biogrid/build/resources/main/biogrid.properties has been removed.
  Output property 'destinationDir' file /home/FILESERVER5/micklem/db539/Projects/git/intermine-git-gradle/intermine/bio/sources/biogrid/build/resources/main/biogrid_additions.xml has been removed.

**Comment by julie-sullivan** [comment] 2019-09-06 06:52
Looking here for breaking changes:

https://docs.gradle.org/current/userguide/upgrading_version_4.html#changes_4.2

**Comment by julie-sullivan** [comment] 2019-09-06 07:48
> I think the issue is related to the processresources task which, for some reason doesn't work properly.

Each bio-source overrides `processResources`, e.g. biogrid has that task in its `build.gradle`. Is the override failing now that we have a newer Gradle version?

**Comment by julie-sullivan** [comment] 2019-09-06 08:22
FYI I don't get this error on Gradle 4.1 (obviously). If I upgrade to use 4.2 I get the error.

**Comment by danielabutano** [comment] 2019-09-06 15:28
Thank you @julie-sullivan who fix the problem.
For now we upgrade to 4.9.
The attempt to update to the latest (5.6.1) failed, with travis no happy

> Execution failed for task ':bio-source-biogrid:mergeModels'.

> java.lang.ClassCastException: org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to org.apache.xerces.xni.parser.XMLParserConfiguration

**Comment by danielabutano** [comment] 2019-09-09 10:22
It seems that moving to 4.9 requires first create a new file, then rename it
`file.createNewFile()
 file.renameTo(modelFilePath)`
For now, only BioSourceDBModelPlugin has been updated, otherwise we have OutOfMemoryError: Metaspace in travis

**Closed** 2019-09-25 10:32 UTC
Labels: gradle, help wanted, in-progress
