### ISSUE TITLE
Python client times out on some queries for some mines

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1406] opened 2016-08-11 08:34 UTC
This script fails:

```
#!/usr/bin/env python

from intermine.webservice import Service
service = Service("http://intermine.wormbase.org/tools/wormmine/service")
query = service.new_query("Gene")
query.add_view(
    "symbol", "secondaryIdentifier", "expressionPatterns.primaryIdentifier",
    "expressionPatterns.lifeStages.anatomyTerms.name",
    "expressionPatterns.lifeStages.anatomyTerms.synonym"
)
query.add_sort_order("Gene.expressionPatterns.primaryIdentifier", "ASC")
for row in query.rows():
    print row["symbol"], row["secondaryIdentifier"], row["expressionPatterns.primaryIdentifier"], \
        row["expressionPatterns.lifeStages.anatomyTerms.name"], \
        row["expressionPatterns.lifeStages.anatomyTerms.synonym"]
```

But works on the site: http://intermine.wormbase.org/tools/wormmine/template.do?name=show_expression_of_a_given_gene Returns 2 million+ records. Maybe that's the issue?

@tharris What is the error message in the Tomcat logs? I can't reproduce this issue in FlyMine.

@justinccdev Can you coordinate with Todd to fix this issue in WormMine? The query works on the site so has to be a client issue. Do you think? However, I can run a query (return all proteins and genes, 5 million+ records) on beta flymine and it works just fine. Maybe because only one table?

Also an issue in Yeastmine. Can you help @kkarra fix? http://yeastmine.yeastgenome.org/yeastmine/template.do?name=Gene_SpellExpressionScores

**Comment by julie-sullivan** [comment] 2016-08-11 08:36
When I tried this query

```
from intermine.webservice import Service
service = Service("http://intermine.wormbase.org/tools/wormmine/service")
query = service.new_query("Gene")
query.add_view(
    "symbol", "expressionPatterns.primaryIdentifier",
    "expressionPatterns.lifeStages.primaryIdentifier",
    "expressionPatterns.subcellularLocalization", "expressionPatterns.pattern",
    "expressionPatterns.lifeStages.anatomyTerms.name"
)
query.add_sort_order("Gene.expressionPatterns.primaryIdentifier", "ASC")

for row in query.rows():
    print row["symbol"], row["expressionPatterns.primaryIdentifier"], \
        row["expressionPatterns.lifeStages.primaryIdentifier"], \
        row["expressionPatterns.subcellularLocalization"], row["expressionPatterns.pattern"], \
        row["expressionPatterns.lifeStages.anatomyTerms.name"]

```

I got this error

```
intermine.errors.WebserviceError: [Errno 502] Proxy Error: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>502 Proxy Error</title>\n</head><body>\n<h1>Proxy Error</h1>\n<p>The proxy server received an invalid\r\nresponse from an upstream server.<br />\r\nThe proxy server could not handle the request <em><a href="/tools/wormmine/service/query/results">POST&nbsp;/tools/wormmine/service/query/results</a></em>.<p>\nReason: <strong>Error reading from remote server</strong></p></p>\n<hr>\n<address>Apache/2.2.31 (Amazon) Server at intermine.wormbase.org Port 80</address>\n</body></html>\n'
```

Which might be a timeout?

**Comment by justinccdev** [comment] 2016-08-11 10:40
This script which mimics the template constraint does work

```
#!/usr/bin/env python

from intermine.webservice import Service
service = Service("http://intermine.wormbase.org/tools/wormmine/service")

query = service.new_query("Gene")

query.add_view(
    "symbol", "secondaryIdentifier", "expressionPatterns.primaryIdentifier",
    "expressionPatterns.lifeStages.anatomyTerms.name",
    "expressionPatterns.lifeStages.anatomyTerms.synonym"
)
query.add_sort_order("Gene.expressionPatterns.primaryIdentifier", "ASC")

query.add_constraint("Gene", "LOOKUP", "lin-3", code = "A")

for row in query.rows():
    print row["symbol"], row["secondaryIdentifier"], row["expressionPatterns.primaryIdentifier"], \
        row["expressionPatterns.lifeStages.anatomyTerms.name"], \
        row["expressionPatterns.lifeStages.anatomyTerms.synonym"]
```

The 500 error text you are seeing does originate from InterMine at WebServiceConstants.SERVICE_FAILED_MSG.  The actual internal exception is logged within WebService.sendError().  So @tharris, @kkarra, we need to see the log message to make progress.

Constraining the requested number of results by specifying a size parameter on the query of the failing script

```
query.rows(size = 10)
```

where this parameter is passed in through the webservice generates the same 500 server error.

**Comment by justinccdev** [comment] 2016-08-11 10:58
Direct request by url works

http://intermine.wormbase.org/tools/wormmine/service/query/results?query=%3Cquery%20name%3D%22%22%20model%3D%22genomic%22%20view%3D%22Gene.symbol%20Gene.secondaryIdentifier%20Gene.expressionPatterns.primaryIdentifier%20Gene.expressionPatterns.lifeStages.anatomyTerms.name%20Gene.expressionPatterns.lifeStages.anatomyTerms.synonym%22%20sortOrder%3D%22Gene.expressionPatterns.primaryIdentifier%20asc%22%3E%3C%2Fquery%3E

**Comment by justinccdev** [comment] 2016-08-11 10:59
And it turns out the same request by an equivalent Perl script works.

```
#!/usr/bin/perl

######################################################################
# This is an automatically generated script to run your query.
# To use it you will require the InterMine Perl client libraries.
# These can be installed from CPAN, using your preferred client, eg:
#
#    sudo cpan Webservice::InterMine
#
# For help using these modules, please see these resources:
#
#  * https://metacpan.org/pod/Webservice::InterMine
#       - API reference
#  * https://metacpan.org/pod/Webservice::InterMine::Cookbook
#       - A How-To manual
#  * http://intermine.readthedocs.org/en/latest/web-services
#       - General Usage
#  * http://iodoc.labs.intermine.org
#       - Reference documentation for the underlying REST API
#
######################################################################

use strict;
use warnings;

# Set the output field separator as tab
$, = "\t";
# Print unicode to standard out
binmode(STDOUT, 'utf8');
# Silence warnings when printing null fields
no warnings ('uninitialized');

# This code makes use of the Webservice::InterMine library.
# The following import statement sets WormMine as your default
use Webservice::InterMine 0.9904 'http://intermine.wormbase.org/tools/wormmine';

# Description: Returns a list of cells/tissues where a specific gene is
# expressed.

my $query = new_query(class => 'Gene');

# The view specifies the output columns
$query->add_view(qw/
    symbol
    secondaryIdentifier
    expressionPatterns.primaryIdentifier
    expressionPatterns.lifeStages.anatomyTerms.name
    expressionPatterns.lifeStages.anatomyTerms.synonym
/);

# Your custom sort order is specified with the following code:
$query->add_sort_order('expressionPatterns.primaryIdentifier', 'ASC');

# Use an iterator to avoid having all rows in memory at once.
my $it = $query->iterator();
while (my $row = <$it>) {
    print $row->{'symbol'}, $row->{'secondaryIdentifier'},
        $row->{'expressionPatterns.primaryIdentifier'},
        $row->{'expressionPatterns.lifeStages.anatomyTerms.name'},
        $row->{'expressionPatterns.lifeStages.anatomyTerms.synonym'}, "\n";
}
```

So against my expectation this may be something python related.  Will be investigating further.  It would still be very helpful to see the intermine log entry when the 500 server error is generated on the python call.

**Comment by justinccdev** [comment] 2016-09-20 16:47
The question of why the Python client is specifically failing here is still open (though the waters have been muddied by other reports of the Perl client failing for these queries as well).

One possibility is that InterMine via Postgres is reporting inaccurately very high estimated query times for reasonable queries [1].  In which case, one thing to try would be to increase the os.query.max-time setting from the current default of 10^7 ms.  For instance, humanmine and flymine both have this set to 10^9 ms instead.

[1] also contains some other strategies for improving estimated query times though I have not yet tried any of them.

[1] https://lists.intermine.org/pipermail/dev/2010-January/000294.html

**Comment by justinccdev** [comment] 2016-11-15 11:04
@kkarra I believe you were going to try out the query timeout as described above?  Did it resolve the problem?

@tharris Have you also tried this change?

**Comment by kkarra** [comment] 2016-11-16 18:01
I did change the value to  os.query.max-time=1000000000
and in running the python script Julie sent a while ago, I am not encountering any errors, so guess you can close this.

**Comment by julie-sullivan** [comment] 2016-11-21 13:07
Thanks @kkarra! @justinccdev Can you try the script again and let the DIOPT folks know it works now?

**Comment by julie-sullivan** [comment] 2016-11-21 13:08
@justinccdev I just emailed @tharris and the wormmine folks to get them to try this fix.

**Comment by justinccdev** [comment] 2016-11-24 16:00
Okay, I still believe that the root problem is the query time mis-estimation issue in InterMine (which may or may not be fixable at root if we are relying on inaccurate PostgreSQL estimations).

However, the proximal reason is that the Python and Perl libraries do generate different webservice requests.  From capturing outgoing HTTP traffic for the queries above, it turns out that the Perl library generates the query

http://intermine.wormbase.org/tools/wormmine/service/query/results?query=%3Cquery%20model%3D%22genomic%22%20name%3D%22%22%20sortOrder%3D%22Gene.symbol%20asc%20Gene.expressionPatterns.primaryIdentifier%20asc%22%20view%3D%22Gene.symbol%20Gene.secondaryIdentifier%20Gene.expressionPatterns.primaryIdentifier%20Gene.expressionPatterns.lifeStages.anatomyTerms.name%20Gene.expressionPatterns.lifeStages.anatomyTerms.synonym%22%2F%3E&format=json

(decoded)

query=<query model="genomic" name="" sortOrder="Gene.symbol asc Gene.expressionPatterns.primaryIdentifier asc" view="Gene.symbol Gene.secondaryIdentifier Gene.expressionPatterns.primaryIdentifier Gene.expressionPatterns.lifeStages.anatomyTerms.name Gene.expressionPatterns.lifeStages.anatomyTerms.synonym"/>&format=json

whilst the Python library generates the query

http://intermine.wormbase.org/tools/wormmine/service/query/results?query=%3Cquery+longDescription%3D%22%22+model%3D%22genomic%22+name%3D%22%22+sortOrder%3D%22Gene.expressionPatterns.primaryIdentifier+asc%22+view%3D%22Gene.briefDescription+Gene.description+Gene.id+Gene.lastUpdated+Gene.length+Gene.name+Gene.operon+Gene.primaryIdentifier+Gene.score+Gene.scoreType+Gene.secondaryIdentifier+Gene.symbol+Gene.symbol+Gene.secondaryIdentifier+Gene.expressionPatterns.primaryIdentifier+Gene.expressionPatterns.lifeStages.anatomyTerms.name+Gene.expressionPatterns.lifeStages.anatomyTerms.synonym%22%2F%3E&format=json

(decoded)

query=<query longDescription="" model="genomic" name="" sortOrder="Gene.expressionPatterns.primaryIdentifier asc" view="Gene.briefDescription Gene.description Gene.id Gene.lastUpdated Gene.length Gene.name Gene.operon Gene.primaryIdentifier Gene.score Gene.scoreType Gene.secondaryIdentifier Gene.symbol Gene.symbol Gene.secondaryIdentifier Gene.expressionPatterns.primaryIdentifier Gene.expressionPatterns.lifeStages.anatomyTerms.name Gene.expressionPatterns.lifeStages.anatomyTerms.synonym"/>&start=0&format=json

The 2 differences are:

* The Perl library adds "Gene.symbol asc" to the sort order
* The Python library adds "Gene.briefDescription Gene.description Gene.id Gene.lastUpdated Gene.length Gene.operon Gene.score Gene.scoreType" to the view.

The Perl addition turns out not to be important.  However, it looks like the Python addition is enough to trigger the mis-estimation of the query time and the timeout.  Manually eliminating the extra selected columns from the HTTP request allows it to work.  Adding certain columns back to the request triggers the failure (e.g. adding Gene.description and Gene.briefDescription separately is fine, but adding both triggers the 500 failure).

What is making Python add the extra columns, even though we don't request them in a view?  From code inspection, on the

```query = service.new_query("Gene")```

call, the Python library automatically adds all the class view columns, both from Gene itself and its parent classes (hence name, description, briefDescription, etc.).  In fact, in the original python script you can replace 

```
query.add_view(
    "symbol", "secondaryIdentifier", "expressionPatterns.primaryIdentifier",
    "expressionPatterns.lifeStages.anatomyTerms.name",
    "expressionPatterns.lifeStages.anatomyTerms.synonym"
)
```

with 

query.select(
    "symbol", "secondaryIdentifier", "expressionPatterns.primaryIdentifier",
    "expressionPatterns.lifeStages.anatomyTerms.name",
    "expressionPatterns.lifeStages.anatomyTerms.synonym"
)

and it will work just fine, since select() removes the existing columns rather than adding to them.

Why is Python adding these columns even though we don't appear to need them?  I don't know, that may be a question for @alexkalderimis.  We could stop the Python library from doing this but that might affect existing scripts that rely on this behaviour.  The simplest solution here, even if not very satisfactory, may be to put a much bigger query estimation limit in InterMine by default, or perhaps try and fix the root cause of the mis-estimation, though I'm not optimistic that's realistically possible as it looks like the root cause may be in Postgres itself.

**Comment by justinccdev** [comment] 2016-11-24 16:08
Also, looking at the timeout is better since it would be easy for someone to trigger this problem by adding enough columns to the request - you don't need the Python behaviour of adding these automatically for the query root to trigger the problem.

**Comment by julie-sullivan** [comment] 2017-04-27 14:48
@kkarra did this work for you?

**Comment by julie-sullivan** [comment] 2017-05-22 11:07
Can we make python bulid better queries? (Match the Perl queries)

**Comment by kkarra** [comment] 2017-05-23 04:15
sorry, I think it did. will re-check and let you know. (@SAB)

**Closed** 2018-10-25 09:34 UTC
Labels: bug, in-progress
