### ISSUE TITLE
UniprotKB now uses evidence codes from the Evidence Ontology (ECO)

### ISSUE THREAD

**Issue by justinccdev** [intermine/intermine#1099] opened 2015-07-30 15:24 UTC
Sometime since December 2014, UniprotKB SwissProt and Trembl started using evidence ontology codes [1] in evidence property tags instead of the GO evidence codes [2] (IEA, etc.).

For instance, currently in [3], the protein references GO:0003905 with

```
<dbReference type="GO" id="GO:0003905">
  <property type="term" value="F:alkylbase DNA N-glycosylase activity"/>
  <property type="evidence" value="ECO:0000501"/>
  <property type="project" value="InterPro"/>
</dbReference>
```

whereas in December 2014, at least, this was

```
<dbReference type="GO" id="GO:0003905">               
  <property type="term" value="F:alkylbase DNA N-glycosylase activity"/>
  <property type="evidence" value="IEA:InterPro"/>
</dbReference>
```

For now, I have patched this in Synbiomine to extract the code correctly and display additional information in the report.   However, I have only entered codes currently used by Synbiomine data - I'm not sure this is enough for the general case.  Will attach the patch/pull request when I figure out how to do so.

[1] http://bioportal.bioontology.org/ontologies/ECO
[2] http://geneontology.org/page/guide-go-evidence-codes
[3] http://www.uniprot.org/uniprot/Q81UJ9.xml

**Comment by julie-sullivan** [comment] 2015-07-30 15:28
See #160

**Comment by justinccdev** [comment] 2015-07-30 15:30
My current patch is at [1].

[1] https://github.com/synbiomine/intermine/commit/0903395267cdb4ae4ecbb459518e66d194be7a7b

**Comment by justinccdev** [comment] 2015-07-30 15:39
I extracted the set of ECO codes used by my current UniprotKB files with the line

```
egrep -o 'ECO:[[:digit:]]+' * | cut -d : -f 2,3 | sort | uniq
```

But I don't regard this as a general solution - this is just to temporarily resolve the issue so that the Synbiomine refresh doesn't get held up further.  Perhaps somewhere there is a list of all ECO codes that might be used in UniprotKB (though doesn't feel likely).  Otherwise perhaps one might have to end up loading ECO codes as an actual data source.

**Comment by cmdcolin** [comment] 2015-10-05 22:28
I have seen some genes with the ECO code being used as well. I think some with multiple evidence codes are used too, so some jave ECO + IEA for example. Maybe loading the evidence ontology is possible

http://www.evidenceontology.org/Download_%26_Develop.html

**Comment by justinccdev** [comment] 2015-10-06 17:14
Nice find, Colin.  Yeah, https://github.com/evidenceontology/evidenceontology/blob/master/eco.obo looks like a file we should be able to load in much the same way as other obo files like the gene and sequence ontologies.

In fact, loading the ontology may require little or no code change at all, just the creation of a bio/sources/eco source and a project.xml entry.  For instance, if you look at bio/sources/go/project.properties you'll see there's a 

```
have.file.obo = true
```

property which tells InterMine that this source should be loaded as a .obo file.  And then in project.xml one may be able to have something very similar to the go entry, e.g.

```
    <source name="eco" type="eco"> 
      <property name="src.data.file" location="eco.obo"/>
    </source>
```

to trigger the load.

However, I expect that changing the UniprotConverter to reference the ontology entry as an evidence code will be more complicated.

**Comment by julie-sullivan** [comment] 2017-04-07 10:09
Current GO guidance on evidence codes:

http://geneontology.org/page/guide-go-evidence-codes

@rachellyne What do you think about adding an ontology term to the model for GOAnnotation.evidence? Ontologies are useful (lol) but then we would lose the ability to exclude (easily) electronic / low quality annotations. Thoughts?

**Comment by julie-sullivan** [comment] 2017-04-07 12:36
Might be a duplicate of #468

**Comment by rachellyne** [comment] 2017-04-18 12:47
I don't like the idea of not being able to exclude certain annotations (in fact this is essential).  I don't know how to solve this though.  Can we make the GO evidence code generic (i.e not specifically GO) and add an ontology type (or is that what you mean above?).  Why would this mean you can't exclude certain annotations?  Do we even need to specify which ontology the evidence code comes from - if it has an ECO: prefix is that enough?  

The evidence codes used by uniprot are here:
http://www.uniprot.org/help/evidences

We don't load all the uniprot evidence codes in humanMine and FlyMine, but maybe we should!

**Comment by julie-sullivan** [comment] 2017-05-02 14:49
@rachellyne What should I do about this? 

1. UniProt has ECO entries for evidence for GO.

```
<dbReference type="GO" id="GO:0008237">
<property type="term" value="F:metallopeptidase activity"/>
<property type="evidence" value="ECO:0000314"/>
<property type="project" value="UniProtKB"/>
</dbReference>
```

We don't load evidence for GO for UniProt. Even if we did, we don't have ontology terms in the model for GO evidence code. I don't see how to go from ECO to the "IEA" evidence code the other GO sources use.

2. The also use ECO for evidence for comments

```
<evidence key="21" type="ECO:0000269">
<source>
<dbReference type="PubMed" id="12542396"/>
</source>
</evidence>
```

Currently we only use the pubmed ID.

Let me know what you think

**Comment by julie-sullivan** [comment] 2017-05-09 13:37
A model change so waiting until 2.0.

**Comment by julie-sullivan** [comment] 2017-07-07 11:57
We decided not to use the ECO data set for GO. It's not comprehensive.

**Closed by julie-sullivan** 2017-07-07 11:57 UTC
Labels: wontfix
