### ISSUE TITLE
Gradle: logs need sorting out

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1909] opened 2018-10-11 08:52 UTC
In the console I see a lot of this, when I run `builddb` for example:

```
log4j:WARN No appenders could be found for logger (org.intermine.util.PropertiesUtil)
```

I also see: 

```
  [analyse] SLF4J: Class path contains multiple SLF4J bindings.
  [analyse] SLF4J: Found binding in [jar:file:/home/FILESERVER5/micklem/humanbuild/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.7/8095d0b9f7e0a9cd79a663c740e0f8fb31d0e2c8/slf4j-simple-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
  [analyse] SLF4J: Found binding in [jar:file:/home/FILESERVER5/micklem/humanbuild/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-jdk14/1.7.10/13675a57601d9106fe82314fe9eebb9b2d9b13c6/slf4j-jdk14-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
  [analyse] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
  [analyse] SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
```

I see a lot of answers on StackOverflow so maybe not too hard to do? Is the issue that we have conflicting log4j libraries?

**Comment by julie-sullivan** [comment] 2019-01-15 16:47
@danielabutano @sergiocontrino I think you've fixed this?

**Comment by danielabutano** [comment] 2019-01-17 12:16
No, I don't think that we have committed that fix, however we had discovered some duplications...

**Comment by danielabutano** [comment] 2019-01-29 16:26
@julie-sullivan the problem related to the multiple SLF4J binding is caused by this configuration:  https://github.com/intermine/intermine/blob/dev/intermine/objectstore/build.gradle#L27.
We have to remove slf4j from there, it's already configured in the main build.gradle

**Closed** 2019-02-20 14:28 UTC
Labels: gradle
