### ISSUE TITLE
Templates: error changing constraint to ONE OF

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#2098] opened 2019-09-18 10:50 UTC
https://beta.humanmine.org/beta/template.do?name=GeneExpress&scope=all

1. run the template with default values
2. change `Atlas Expression > Type` to ONE OF, run template
3. go back, run again and I get this error

Related to #2044? Something is up with ONE OF constraints.

```


---- Error Found ----

java.lang.NullPointerException: Cannot create a multivalue constrait with a null  
collection of values.at org.intermine.pathquery.PathConstraintMultiValue.<init>
(PathConstraintMultiValue.java:58)at 
org.intermine.api.template.TemplatePopulator.setConstraint(TemplatePopulator.java:284)
at org.intermine.api.template.TemplatePopulator.getPopulatedTemplate(TemplatePopulator.java:90)at org.intermine.web.struts.TemplateAction.execute(TemplateAction.java:161)
at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:462)at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)at org.intermine.web.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:139)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)at org.intermine.web.filters.PermanentURLFilter.doFilter(PermanentURLFilter.java:60)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685)at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)at java.lang.Thread.run(Thread.java:748)
```

**Comment by sergiocontrino** [comment] 2020-01-17 10:44
we (@rachellyne  and i) cannot reproduce this in the recently released production humanmine. closing for now.

**Closed** 2020-01-17 10:45 UTC
Labels: bug
